configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-fragrant-dew-a1me50bu-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Yq0KlhuNmRb8
